apiVersion: batch/v1
kind: Job
metadata:
  name: busybox-load-test
  namespace: test-load
spec:
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["/bin/sh", "-c"]
        args:
        - |
          while true; do
            for i in $(seq 1 100); do
              wget -q -O- http://test-app-service.test-load.svc.cluster.local &
            done
            sleep 1
          done
      restartPolicy: Never
  backoffLimit: 1
