apiVersion: batch/v1
kind: Job
metadata:
  name: load-test
  namespace: test-load
spec:
  template:
    spec:
      containers:
      - name: load-test
        image: rakyll/hey
        command: ["./hey"]
        args: ["-z", "5m", "-q", "30", "-c", "50", "http://test-app-service.test-load.svc.cluster.local"]
      restartPolicy: Never
  backoffLimit: 4
